spring.application.name=discovery-service

server.port=8100

#Eureka server will NOT try to register itself
eureka.client.register-with-eureka=false

#It will NOT try to discover other services
eureka.client.fetch-registry=false


