spring.application.name=mentorship-service

spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=mentorshipdb

spring.cloud.compatibility-verifier.enabled=false

eureka.client.service-url.defaultZone=http://localhost:8100/eureka

server.port=8085

eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=true

app.jwt.secret=${JWT_SECRET:mini-project-local-dev-secret-change-this-32}
