#spring.application.name=EXPERIENCE-SERVICE
#spring.data.mongodb.uri=mongodb://localhost:27017/experiencedb

spring.application.name=experience-service

spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=experiencedb

spring.cloud.compatibility-verifier.enabled=false

eureka.client.service-url.defaultZone=http://localhost:8100/eureka

server.port=8082

eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=true

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9090/realms/mini-project

spring.kafka.producer.bootstrap-servers=localhost:29092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
